Ml api integration
TheWITProject/MentorApp pull request #93
Opened 2020-06-10 16:05 UTC by ezronis

2020-06-10 21:45 UTC, jremmanue requested changes

2020-06-10 21:45 UTC, jremmanue commented on match/admin.py
> +# class MatchesAdmin(admin.ModelAdmin):
i would remove commented out code

2020-06-10 21:45 UTC, jremmanue commented on match/admin.py
> +    def set_immortal(self, request):
i would clean this up so variables make sense

2020-06-10 21:45 UTC, jremmanue commented on match/templates/buttons.html
> +        <form action="immortal/" method="POST">
again maybe change immortal/mortal thing to contextualize into app

2020-06-10 21:45 UTC, jremmanue commented on ml/mentor_match_classifier/mentor_match.py
> +            print(prediction)
remove print statment

2020-06-10 21:45 UTC, jremmanue commented on ml/mentor_match_classifier/mentor_match_utils.py
> +        # if(region == 0):     #if the mentor/mentee have dif regions
remove commented out

2020-06-10 21:45 UTC, jremmanue commented on survey/exporter/csv/survey2csv.py
> +        # header += [_("user_id")]
remove line

2020-06-10 21:45 UTC, jremmanue commented on survey/exporter/csv/survey2csv.py
> +        print(response)
remove print statements

2020-06-12 14:58 UTC, ezronis commented on userProfile/admin.py
> +
@amaliatorres2 are these changes still valid?

2020-06-12 14:58 UTC, ezronis commented on userProfile/models.py
> +    answer = models.ForeignKey(Answer,on_delete=models.CASCADE, limit_choices_to=Q(question_id = 1), null=True)
@amaliatorres2 are these changes still valid?

2020-06-12 14:58 UTC, ezronis commented on userProfile/models.py
> +    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
@amaliatorres2 are these changes still valid?

2020-06-12 14:58 UTC, ezronis commented on userProfile/templates/pages/edit_profile.html
> +      {% for field in add_form%}
@amaliatorres2 are these changes still valid?

2020-06-12 14:58 UTC, ezronis commented on userProfile/views.py
> +        'profile_form': profile_form,
@amaliatorres2 are these changes still valid?

2020-06-12 15:07 UTC, amaliatorres2 commented on userProfile/models.py
> +    answer = models.ForeignKey(Answer,on_delete=models.CASCADE, limit_choices_to=Q(question_id = 1), null=True)
no

2020-06-12 15:07 UTC, amaliatorres2 commented on userProfile/models.py
> +    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
no

2020-06-12 15:07 UTC, amaliatorres commented on userProfile/templates/pages/edit_profile.html
> +      {% for field in add_form%}
no

2020-06-12 15:08 UTC, amaliatorres2 commented on userProfile/views.py
> +        'profile_form': profile_form,
no

2020-06-15 23:46 UTC, merged